[package]
name = "day_18"
version = "0.1.0"
authors = ["ekuecks <kueckse@gmail.com>"]
edition = "2018"

[features]
part1 = []
part2 = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
